### ISSUE TITLE
USGS sites should include a geographic plot

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/ILAMB-Watersheds#2]
Perhaps we can use a tile set from cartopy, query the watershed shape file and plot lay/lon of where the site is located for context.

**Comment by jitendra-kumar** [comment]
@nocollier : I have prototyped this plot in a standalone script here. https://github.com/jitendra-kumar/hydrology_codes/blob/8ca54899ef702e92498691a2b5014c6dcc7458b6/plot_usgs_site_basins.py 

We can discuss, update and integrate it within ILAMB.
